version: '3.7'

services: 
    influxdb:
        image: mendhak/arm32v6-influxdb
        container_name: influxdb
        ports: 
            - 8086:8086
        volumes: 
            - ./influxdbdata:/root/.influxdb/data/
